/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;


import koneksi.koneksi;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author HP
 */
public class FormMobil extends javax.swing.JFrame {

private DefaultTableModel tabmode;
    private koneksi obj;
    private DefaultTableModel mobil;
    /**
     * Creates new form FormMobil
     */
    
    
    
    public FormMobil() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        mobil = new DefaultTableModel();
        tabelMobil.setModel(mobil);
        mobil.addColumn("Id Mobil");
        mobil.addColumn("Merek Mobil");
        mobil.addColumn("Model Mobil");
        mobil.addColumn("Tahun");
        mobil.addColumn("Warna");
        mobil.addColumn("Plat Nomor");
        mobil.addColumn("Harga Sewa Perhari");
        mobil.addColumn("Status");
       
        tampilmobil();
    }

public void tampilmobil() {
   try {
            mobil.setRowCount(0);

            String query = "SELECT * FROM mobil";
            try (java.sql.PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[8];
                    line[0] = data.getString("id_mobil");
                    line[1] = data.getString("merek");
                    line[2] = data.getString("model");
                    line[3] = data.getString("tahun");
                    line[4] = data.getString("warna");
                    line[5] = data.getString("plat_nomor");
                    line[6] = data.getString("harga_sewa_perhari");
                    line[7] = data.getString("status");
                    mobil.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMerek = new javax.swing.JTextField();
        tfModel = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        tfWarna = new javax.swing.JTextField();
        tfPlatNomor = new javax.swing.JTextField();
        tfHargaSewaPerhari = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMobil = new javax.swing.JTable();
        tfStatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfIdMobil = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM DATA MOBIL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 20));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 603, 47);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Merek                           :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Model                            :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tahun                             :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Warna                             :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Plat Nomor                    :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga Sewa Perhari     :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status                              :");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabelMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Mobil", "Merek Mobil", "Model Mobil", "Tahun", "Warna", "Plat Nomor", "Harga Sewa Perhari", "Status"
            }
        ));
        tabelMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMobil);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id Mobil                        :");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMerek, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tfModel)
                            .addComponent(tfTahun)
                            .addComponent(tfWarna)
                            .addComponent(tfPlatNomor)
                            .addComponent(tfHargaSewaPerhari)
                            .addComponent(tfStatus)
                            .addComponent(tfIdMobil)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBersihkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari)
                            .addComponent(btnCetak)))
                    .addComponent(jScrollPane1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfPlatNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfHargaSewaPerhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnBersihkan)
                    .addComponent(btnHapus)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 53, 590, 630);

        setSize(new java.awt.Dimension(619, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        btnKembali.setVisible(false);
        new FormUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
           if (tfIdMobil.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, " Id mobil belum di isi");
               tfIdMobil.requestFocus();
           } else if (tfMerek.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Merek mobil belum di isi");
               tfMerek.requestFocus();
           } else if (tfModel.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Model mobil belum di isi");
               tfModel.requestFocus();
           } else if (tfTahun.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tahun mobil belum di isi");
               tfTahun.requestFocus(); 
           } else if (tfWarna.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Warna mobil belum diisi");
               tfWarna.requestFocus();
           } else if (tfPlatNomor.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Warna mobil belum diisi");
               tfPlatNomor.requestFocus();
           } else if (tfHargaSewaPerhari.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Warna mobil belum diisi");
               tfHargaSewaPerhari.requestFocus();
           } else if (tfStatus.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Warna mobil belum diisi");
               tfStatus.requestFocus();
           } else {
               String sql;
               sql = "insert into mobil value('"+tfIdMobil.getText()+"','"+tfMerek.getText()+"','"+tfModel.getText()+"','"+tfTahun.getText()+"','"+tfWarna.getText()+"'"
                       + ",'"+tfPlatNomor.getText()+"','"+tfHargaSewaPerhari.getText()+"','"+tfStatus.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
           tampilmobil();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        } 
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        tfIdMobil.setText("");
        tfMerek.setText("");
        tfModel.setText("");
        tfTahun.setText("");
        tfWarna.setText("");
        tfPlatNomor.setText("");
        tfHargaSewaPerhari.setText("");
        tfStatus.setText("");
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    try {
    if (tfIdMobil.getText().isEmpty() || tfMerek.getText().isEmpty() ||
        tfModel.getText() .isEmpty() || tfTahun.getText().isEmpty() || 
        tfWarna.getText().isEmpty() || tfPlatNomor.getText().isEmpty() ||
        tfHargaSewaPerhari.getText().isEmpty() || tfStatus.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
        } else {
            // Menampilkan dialog konfirmasi sebelum menghapus
            int confirmDialogResult = JOptionPane.showConfirmDialog(this,
                    "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            // Jika pengguna mengonfirmasi untuk menghapus
            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                // Query SQL untuk menghapus data dari tabel
                String sql = "DELETE FROM mobil WHERE id_mobil=?";
                
                // Menggunakan try-with-resources untuk PreparedStatement
                try (java.sql.PreparedStatement hapus = obj.konek.prepareStatement(sql)) {
                    hapus.setString(1, tfIdMobil.getText());
                    
                    // Menjalankan query DELETE dan mendapatkan jumlah baris yang terpengaruh
                    int rowsAffected = hapus.executeUpdate();

                    // Jika ada baris yang terpengaruh, berarti data berhasil dihapus
                    if (rowsAffected > 0) {
                        tampilmobil();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                    } else {
                        // Jika tidak ada baris yang terpengaruh, berarti data tidak ditemukan
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data. Data tidak ditemukan.");
                    }
                }
            }
        }
    } catch (SQLException | HeadlessException e) {
        // Menangani kesalahan dan menampilkan pesan kesalahan kepada pengguna
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    try {
    if (tfIdMobil.getText().isEmpty() || tfMerek.getText().isEmpty() ||
        tfModel.getText() .isEmpty() || tfTahun.getText().isEmpty() || 
        tfWarna.getText().isEmpty() || tfPlatNomor.getText().isEmpty() ||
        tfHargaSewaPerhari.getText().isEmpty() || tfStatus.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
    } else {
        // Bagian untuk INSERT
        String sqlInsert = "INSERT INTO mobil (id_mobil, merek, model, tahun, warna, plat_nomor, harga_sewa_perhari, status) " +
                           "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement insertmobil = obj.konek.prepareStatement(sqlInsert);

        insertmobil.setString(1, tfIdMobil.getText());
        insertmobil.setString(2, tfMerek.getText());
        insertmobil.setString(3, tfModel.getText());
        insertmobil.setString(4, tfTahun.getText());
        insertmobil.setString(5, tfWarna.getText());
        insertmobil.setString(6, tfPlatNomor.getText());
        insertmobil.setString(7, tfHargaSewaPerhari.getText());
        insertmobil.setString(8, tfStatus.getText());

        // Bagian untuk UPDATE
        String sqlUpdate = "UPDATE mobil SET merek=?, model=?, tahun=?, warna=?, plat_nomor=?, harga_sewa_perhari=?, status=? WHERE id_mobil=?";
        java.sql.PreparedStatement updatemobil = obj.konek.prepareStatement(sqlUpdate);

        updatemobil.setString(1, tfIdMobil.getText());
        updatemobil.setString(2, tfMerek.getText());
        updatemobil.setString(3, tfModel.getText());
        updatemobil.setString(4, tfTahun.getText());
        updatemobil.setString(5, tfWarna.getText());
        updatemobil.setString(6, tfPlatNomor.getText());
        updatemobil.setString(7, tfHargaSewaPerhari.getText());
        updatemobil.setString(8, tfStatus.getText());
       

        // Eksekusi query UPDATE
        int hasilUpdate = updatemobil.executeUpdate();

        // Eksekusi query INSERT jika tidak ada baris yang terupdate
        if (hasilUpdate == 0) {
            int hasilInsert = insertmobil.executeUpdate();

            if (hasilInsert > 0) {
                tampilmobil();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data. Pastikan Kode yang dimasukkan benar.");
            }
        } else {
            tampilmobil();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}    
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tabelMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMobilMouseClicked
        // TODO add your handling code here:
        int baris = tabelMobil.getSelectedRow();
        String id_mobil = tabelMobil.getValueAt(baris, 0).toString();
        String merek = tabelMobil.getValueAt(baris, 1).toString();
        String model = tabelMobil.getValueAt(baris, 2).toString();
        String tahun = tabelMobil.getValueAt(baris, 3).toString();
        String warna = tabelMobil.getValueAt(baris, 4).toString();
        String plat_nomor = tabelMobil.getValueAt(baris, 5).toString();
        String harga_sewa_perhari = tabelMobil.getValueAt(baris, 6).toString();
        String status = tabelMobil.getValueAt(baris, 7).toString();
        tfIdMobil.setText(id_mobil);
        tfMerek.setText(merek);
        tfModel.setText(model);
        tfTahun.setText(tahun);
        tfWarna.setText(warna);
        tfPlatNomor.setText(plat_nomor);
        tfHargaSewaPerhari.setText(harga_sewa_perhari);
        tfStatus.setText(status);
    }//GEN-LAST:event_tabelMobilMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         String cari = tfCari.getText();

    try {
        mobil.setRowCount(0);

        String query = "SELECT * FROM mobil WHERE merek LIKE '%" + cari + "%'"
                + "OR model LIKE '%" + cari + "%'"
                + "OR tahun LIKE '%" + cari + "%'"
                + "OR warna LIKE '%" + cari + "%'"
                + "OR plat_nomor LIKE '%" + cari + "%'"
                + "OR harga_sewa_perhari LIKE '%" + cari + "%'"
                + "OR status LIKE '%" + cari + "%'";
        try (java.sql.PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
             ResultSet data = preparedStatement.executeQuery()) {
            while (data.next()) {
                Object[] line = new Object[8];
                line[0] = data.getString("id_mobil");
                line[1] = data.getString("merek");
                line[2] = data.getString("model");
                line[3] = data.getString("tahun");
                line[4] = data.getString("warna");
                line[5] = data.getString("plat_nomor");
                line[6] = data.getString("harga_sewa_perhari");
                line[7] = data.getString("status");
                mobil.addRow(line);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        String path = ".\\src\\report\\reportDataMobil.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/aplikasirentalmobil", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMobil;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHargaSewaPerhari;
    private javax.swing.JTextField tfIdMobil;
    private javax.swing.JTextField tfMerek;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfPlatNomor;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfTahun;
    private javax.swing.JTextField tfWarna;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
